[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://aahar-express-f.vercel.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# Handle OPTIONS preflight requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cors-preflight"
  status = 200
  force = true
  conditions = {Method = ["OPTIONS"]}

# For testing: Route auth requests to mock auth function
[[redirects]]
  from = "/api/auth/signin"
  to = "/.netlify/functions/auth-mock"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/signup"
  to = "/.netlify/functions/auth-mock"
  status = 200
  force = true

# For all other API routes, proxy to your Spring Boot API if it's hosted elsewhere
# (Remove this if your Spring Boot app is deployed with Netlify)
[[redirects]]
  from = "/api/*"
  to = "https://your-spring-boot-api-url.com/api/:splat"
  status = 200
  force = true

# Fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 