[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://aahar-express-f.vercel.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# Handle OPTIONS preflight requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cors-preflight"
  status = 200
  force = true
  conditions = {Method = ["OPTIONS"]} 